version: '3'

networks:
  web-network:

services:


  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - mysql
      - php-fpm
    networks:
      - web-network

  php-fpm:
    build: 
      context: ./php-fpm
      dockerfile: ./Dockerfile
    container_name: php-fpm
    ports:
      - "9000:9000"
    tty: true
    volumes:
      - ./app:/var/www
    networks:
      - web-network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - web-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - web-network